# Manejo de excepciones

Los errores de ejecución son llamados comúnmente excepciones y por eso de ahora en adelante utilizaremos ese nombre. Durante la ejecución de un programa, si dentro de una función surge una excepción y la función no la maneja, la excepción se propaga hacia la función que la invocó, si esta otra tampoco la maneja, la excepción continúa propagándose hasta llegar a la función inicial del programa y si esta tampoco la maneja se interrumpe la ejecución del programa.

Para el manejo de excepciones los lenguajes proveen ciertas palabras reservadas, que nos permiten manejar las excepciones que puedan surgir y tomar acciones de recuperación para evitar la interrupción del programa o, al menos, para realizar algunas acciones adicionales antes de interrumpir el programa.

El manejo de excepciones se hace mediante los bloques que utilizan las sentencias `try`, `except` y `finally`.

[w3school](https://www.w3schools.com/python/python_try_except.asp)